### ISSUE TITLE
Add a detail description of Whales micro-service architecture on "Why" section

### ISSUE THREAD

**Issue by mayra-cabrera** [Gueils/whales#13]
This is the same as this [one](https://github.com/WhalesIL/belugas/issues/18), so I'm just gonna go and copy the same content
________

On README we have a small [section](https://github.com/WhalesIL/whales#why) titled "Why?". The purpose of this section is to explain what is the Whales ecosystem, and how does it work. 

The _how does it work_ part is missing, any ideas of how we can explain it, in a way that is interesting and compelling? 

Maybe a drawing of the architecture?

Thoughts? @vovimayhem @kurenn @thelastinuit

**Comment by n0um3n4** [comment]
the idea of an architecture sounds good and text of course.
How about the following: a draw that diagram you want, write something and then we iterate over that, huh?
